### ISSUE TITLE
Heading does not work

### ISSUE THREAD

**Issue by chaco** [IOC/dokuwiki-aceeditor#10]
Hello,

After installing Aceeditor on DW-Angua it is not possible to add a heading on an empty page in the ACE view (nothing is inserted).
In the standard DW editor it works as expected.

Is that a known issue?

Thanks in advance!

**Comment by albertgasset** [comment]
No, it should work. Are you using the last version of the plugin?

**Comment by chaco** [comment]
Yes.
Ok I will try it again using only ACE (without any other plugins). I'll keep you up to date.
Thanks!

**Comment by chaco** [comment]
It seems that an incompatibility with fckglite causes this issue.

**Comment by albertgasset** [comment]
OK, I've added fckglite to the conflicts list in the plugin page.
