### ISSUE TITLE
SSL alert with jquery

### ISSUE THREAD

**Issue by ghost** [IOC/dokuwiki-aceeditor#12]
I get an SSL alert in my browser if I use dokuwiki with https because the external link to jquery doesn't use https. So i suggest to replace in action.php :

 http://code.jquery.com/jquery.min.js     by     https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js

**Comment by albertgasset** [comment]
Which browser are you using?

**Comment by ghost** [comment]
Chromium 18 on ubuntu 12.04, there is a screenshot -> http://img812.imageshack.us/img812/9493/screenshotfrom201205231.png

**Comment by albertgasset** [comment]
I've fixed this in master, it'll be included in the next release. Thank you for reporting this bug.
