### ISSUE TITLE
Navigation shortcuts issues on Mac

### ISSUE THREAD

**Issue by 5lava** [IOC/dokuwiki-aceeditor#13]
"Go to word left" and "Go to word right" navigation shortcuts don't work in neither Chrome 21 nor Safari 6 (OSX 10.8.1).
Could you take a look please?
Thank you in advance.

**Comment by albertgasset** [comment]
You're right, it doesn't work. These shortcuts are from core [Ace](https://github.com/ajaxorg/ace), this Dokuwiki plugin only adds some specific shortcuts. Maybe they will help you better than I can.

**Comment by 5lava** [comment]
Well, Option+Right and Option+Left works fine on Ace's demo page: http://ace.ajax.org/build/kitchen-sink.html

**Comment by albertgasset** [comment]
It actually was a bug, thank you for reporting it.
