### ISSUE TITLE
Inserting Headline using editor buttons deletes page content when Ace is disabled

### ISSUE THREAD

**Issue by lmoellendorf** [IOC/dokuwiki-aceeditor#14]
When Ace is disabled (the editor mode - not the whole plugin) inserting a Headline by using the editor buttons "Same Level Headline", "Lower/Higher Headline" clears the whole page before inserting new headline.

Applies to these versions:
aceeditor-20120417
aceeditor-20120906
dokuwiki-2012-09-10 “Adora Belle” RC1
dokuwiki-2012-01-25b “Angua”

Besides this small bug this is a very useful plugin!

**Comment by albertgasset** [comment]
Thank you for reporting this bug!

**Comment by lexfridman** [comment]
After upgrading to Adora Belle (2012-10-13 version), I am now getting this problem (and I wasn't getting it before thanks to your fix 2 months ago).

**Comment by albertgasset** [comment]
Sorry, I can't reproduce it. Are you sure is the same case as before?
