### ISSUE TITLE
.ace_editor font family mismatch

### ISSUE THREAD

**Issue by becmer** [IOC/dokuwiki-aceeditor#15]
There is monospace font family setting up for .ace_editor class, but it's overrided by global style with something like Verdana. In effect ace thinks about monospace, but browser displays sans-serif and text caret position is inconsistent.

**Comment by becmer** [comment]
Solved by adding style in plugin's build.js just after .ace_editor style.

.ace_editor \* { font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace !important; }

Please consider making appropriate changes in your code.

**Comment by albertgasset** [comment]
Recently I made a change that sets the font family via javascript, to the one used in the original textarea. So there should be no difference in font properties when enabling/disabling Ace. You'll have to build from source or wait until I release a new version.
