### ISSUE TITLE
Table funtion doesn't work well with non-romanji

### ISSUE THREAD

**Issue by erial** [IOC/dokuwiki-aceeditor#18]
Hi, I'm a Korean.
Dokuwiki aceeditor plugin is very great function. I thankfully use this. 

Aceeditor support for dokuwiki syntax, and table function works smoothly work for good readable shape.

But non-romanji character count doesn't work well...

For example, I insert romanji and non-romanji characters, it works like this.

![aceeditor](https://f.cloud.github.com/assets/688661/823749/eb074114-f01f-11e2-8b6e-94dd8692f486.png)

So, table function makes bad shape tables.

I think it is not important bug, just space count system's miss. But if you fix this, many Asian use this plugin more useful.

Thanx for read this. :)

**Comment by albertgasset** [comment]
Thank you for reporting this bug. It's fixed in the new release.
