### ISSUE TITLE
Couldn't load 20110321 version on LEMMING

### ISSUE THREAD

**Issue by erial** [IOC/dokuwiki-aceeditor#4]
DW 2009.12.24 LEMMING Dosen't work with 20110321 version.

20110311 version works (Korean, Multi bytes lang doesn't work well, but load plugin). 

20110321 version DOESN'T WORKS. It load failure for function icons and  ace editor.

I test it several times. but 20110321 version doesn't work on LEMMING

CHECK IT, please :) 

ps. I'm Korean. So I can't input text on ACE editor. but It doesn't matter this plugin, right? Thanks for work for conversion good editor on DW. I really thanks. :)

**Comment by albertgasset** [comment]
What browser are you using? Do you get any JavScript error?

You're right, multi-byte languages are not supported well in Ace, we can not do anything about this.

**Comment by albertgasset** [comment]
I think it's fixed in the new version. Can you confirm this?

**Comment by erial** [comment]
Great! It works! Thanks! :)
