### ISSUE TITLE
Opera cursor position wrong

### ISSUE THREAD

**Issue by aurelije** [IOC/dokuwiki-aceeditor#5]
When using aceedit with Opera 11 cursor position is wrong. It is moved several characters to the left from editing position.

**Comment by albertgasset** [comment]
Sorry, but this bug is not specific to this plugin,, it seems a bug in Ace editor. You could open the issue in their tracker: https://github.com/ajaxorg/ace/issues

**Comment by aurelije** [comment]
Thanks!
