### ISSUE TITLE
conflict with "Discussion" plugin

### ISSUE THREAD

**Issue by mmv-ru** [IOC/dokuwiki-aceeditor#6]
When discussion plugin enabled, normal editor shown but not ace.

Release 2011-05-25a "Rincewind"

Ace Editor plugin  2011-06-14 http://www.dokuwiki.org/plugin:aceeditor
discussion 2010-11-16  http://www.dokuwiki.org/plugin:discussion

I also test with  plugin from github. Do not work.

**Comment by albertgasset** [comment]
I've tested the discussion plugin and have not found any conflict with Ace. Could you give more information (browser, dokuwiki version, error message, etc.)?

**Comment by mmv-ru** [comment]
Thank. I make deeper tests ASAP.

**Comment by mmv-ru** [comment]
Im Sorry. Its not conflict with Discussion.
Its failed to load some *.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/ace/range.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/ace/keyboard/state_handler.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/ace/editor.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/ace/mode/text.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/ace/virtual_renderer.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/pilot/canon.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/ace/undomanager.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/ace/tokenizer.js
/var/www/routerz/data/www/docuwiki.routerz.ru/lib/plugins/aceeditor/scripts/pilot/fixoldbrowsers.js

I dont know how it must work, but aceeditor/scripts/ace and aceeditor/scripts/plot is files with paths
../ace/lib/ace/
../ace/support/pilot/lib/pilot/

to not existing directories.
installed on Dokuwiki 2011-05-25a "Rincewind"

I fix it. 
Get all submodules (ace, pilot) and replace aceeditor/scripts/ace aceeditor/scripts/cocpit aceeditor/scripts/pilot by symlinks

Look like error in build process.
