### ISSUE TITLE
DokuWiki's internal Js breaks with Ace Editor enabled

### ISSUE THREAD

**Issue by ofpiyush** [IOC/dokuwiki-aceeditor#7]
I am not sure why this happens as I am not very good with js but it doesnt work :(
Ace editor itself however works fine without any issues but other js die.

**Comment by albertgasset** [comment]
We need more information to help you. What error message is shown? Which browser/version are you using?

**Comment by ofpiyush** [comment]
I was using firefox 5 at that time. the problem continues in firefox 6 too. I just tested it to be broken in chrome 13 too.
Are you aware that DokuWiki moved to jQuery? May be that is causing this issue. the editor itself works just fine. (I had not used it before though it seems to be working)

I was developing a plugin and was using some javascript to have select all/ select none and confirm delete options. They didnt work when ace editor plugin was enabled. so then I started testing other things and found that none of the internal DokuWiki behaviours are working with this plugin enabled. May be some clash of naming?

**Comment by albertgasset** [comment]
I'm aware Dokuwiki is moving to jQuery in the next version, and the ace editor plugin is not ported yet. Are you using a developement branch of Dokuwiki?

**Comment by ofpiyush** [comment]
yes. so that is what must be breaking it! :D

**Comment by albertgasset** [comment]
OK, I'll try to port the plugin before the release.
