### ISSUE TITLE
PHP error when attempting to edit a page

### ISSUE THREAD

**Issue by logomancer** [IOC/dokuwiki-aceeditor#9]
When attempting to edit a page with aceeditor enabled, I get the following error:

_Fatal error:_ Call to undefined function json_encode() in _/path/to/wiki/lib/plugins/aceeditor/action.php_ on line _66_

I am running DokuWiki Angua RC1 with the following settings:

Syntax highlighting: Enabled
Text wrapping limit: 80
Color theme: TextMate
Enable support for LaTeX plugin: Enabled

It's also running with the MathJax plugin, if that makes a difference.

**Comment by albertgasset** [comment]
The function "json_encode" is part of the PHP extension "JSON", which is bundled into PHP 5.2. You may need to enable or install this extension.

**Comment by logomancer** [comment]
My mistake. Thanks!
